name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${plugin.mainClass}
depend: [WGCustomFlags, WorldGuard]
permissions:
  pvptimeout.bypass.*:
    description: Allows you to be ignored by PvpTimeout
    default: false
    children:
      pvptimeout.bypass.attacked: true
      pvptimeout.bypass.attacker: true
  pvptimeout.bypass.attacked:
    description: Allows you to be ignored by PvpTimeout when you are attacked
    default: false
  pvptimeout.bypass.attacker:
    description: Allows you to be ignored by PvpTimeout when you attack
    default: false